# Generated by Django 6.0.6 on 2026-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='زیرعنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='تصویر')),
                ('cta_label', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه')),
                ('cta_link', models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیر (فقط خدمات)')),
            ],
            options={
                'verbose_name': 'اسلاید هیرو',
                'verbose_name_plural': 'اسلایدهای هیرو',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('body', models.TextField(blank=True, verbose_name='محتوا')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیر (فقط خدمات)')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='برند ما', max_length=120, verbose_name='نام برند')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='شعار')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='لوگو')),
                ('about', models.TextField(blank=True, verbose_name='درباره ما')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='واتساپ')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('hero_badge', models.CharField(blank=True, default='برند مورد اعتماد شما', max_length=100, verbose_name='متن بج هیرو')),
                ('hero_title_line1', models.CharField(blank=True, default='تجربه\u200cای نو از', max_length=150, verbose_name='عنوان هیرو - خط اول')),
                ('hero_title_line2', models.CharField(blank=True, default='کیفیت و خدمات', max_length=150, verbose_name='عنوان هیرو - خط دوم (رنگی)')),
                ('hero_subtitle', models.TextField(blank=True, default='محصولاتی که می\u200cتوانید به آن\u200cها اعتماد کنید، در کنار خدمات پس از فروشی که خیال شما را راحت می\u200cکند.', verbose_name='متن توضیح هیرو')),
                ('hero_bg_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='عکس بک\u200cگراند هیرو')),
                ('hero_product_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='عکس محصول هیرو')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حالت تعمیر (فقط خدمات)')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
