# Generated by Django 6.0.6 on 2026-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='page_headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات سربرگ صفحات'),
        ),
    ]
