# Generated by Django 6.0.6 on 2026-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_spare_part',
            field=models.BooleanField(default=False, verbose_name='قطعه یدکی'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_products',
            field=models.BooleanField(default=True, verbose_name='نمایش در محصولات'),
        ),
    ]
