# Generated by Django 6.0.6 on 2026-08-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_spare_part_product_show_in_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='catalog.product', verbose_name='محصول اصلی'),
        ),
    ]
