# Generated by Django 6.0.6 on 2026-08-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('product_model', models.CharField(blank=True, max_length=200, verbose_name='مدل کالا')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='شماره سریال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('message', models.TextField(verbose_name='متن انتقاد و پیشنهادات')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'انتقاد / پیشنهاد',
                'verbose_name_plural': 'انتقادات و پیشنهادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('request_type', models.CharField(choices=[('repair', 'تعمیر'), ('warranty', 'گارانتی'), ('install', 'نصب و راه\u200cاندازی'), ('question', 'سوال / راهنمایی'), ('other', 'سایر')], default='repair', max_length=20, verbose_name='نوع درخواست')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='نام محصول')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='شماره سریال')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('description', models.TextField(verbose_name='شرح مشکل / درخواست')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='after_sales/', verbose_name='پیوست')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('waiting', 'در انتظار مشتری'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست خدمات پس از فروش',
                'verbose_name_plural': 'درخواست\u200cهای خدمات پس از فروش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('service', 'نظرسنجی خدمات'), ('product', 'نظرسنجی محصول')], default='service', max_length=10, verbose_name='نوع نظرسنجی')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('agency_name', models.CharField(blank=True, max_length=200, verbose_name='نام نمایندگی مورد نظر')),
                ('service_quality', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='کیفیت خدمات ارائه شده')),
                ('staff_behavior', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='نحوه برخورد پرسنل')),
                ('service_duration', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='مدت زمان ارائه خدمات')),
                ('staff_knowledge', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='ارزیابی دانش فنی پرسنل')),
                ('service_cost', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='ارزیابی هزینه ارائه خدمات')),
                ('info_method', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('average', 'متوسط'), ('poor', 'ضعیف')], max_length=20, verbose_name='نحوه اطلاع\u200cرسانی')),
                ('product_model', models.CharField(blank=True, max_length=200, verbose_name='مدل کالا')),
                ('purchase_date_survey', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('serial_number_survey', models.CharField(blank=True, max_length=120, verbose_name='شماره سریال')),
                ('feedback_message', models.TextField(blank=True, verbose_name='متن انتقاد و پیشنهادات')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کدملی')),
                ('purchased_recently', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], max_length=5, verbose_name='خرید در ۶ ماه اخیر')),
                ('selected_item', models.CharField(blank=True, max_length=200, verbose_name='آیتم انتخابی')),
                ('future_purchase', models.CharField(blank=True, max_length=200, verbose_name='قصد خرید در آینده')),
                ('current_product_usage', models.CharField(blank=True, max_length=200, verbose_name='محصول فعلی در منزل')),
                ('home_appliance_models', models.CharField(blank=True, max_length=300, verbose_name='مدل لوازم خانگی در منزل')),
                ('top_brands', models.CharField(blank=True, max_length=300, verbose_name='سه برند محبوب')),
                ('recommend', models.CharField(blank=True, choices=[('yes', 'بله'), ('no', 'خیر')], max_length=5, verbose_name='توصیه به دیگران')),
                ('best_iranian_brand', models.CharField(blank=True, max_length=200, verbose_name='موفق\u200cترین برند ایرانی')),
                ('product_suggestion', models.CharField(blank=True, max_length=300, verbose_name='پیشنهاد محصول برای تکمیل سبد')),
                ('comment', models.TextField(blank=True, verbose_name='پیشنهادات / نظر')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز کلی (۱ تا ۵)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='after_sales.servicerequest', verbose_name='درخواست مرتبط')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
