# Generated by Django 6.0.6 on 2026-08-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('tehran', 'تهران'), ('alborz', 'البرز'), ('isfahan', 'اصفهان'), ('fars', 'فارس'), ('khorasan-razavi', 'خراسان رضوی'), ('azerbaijan-east', 'آذربایجان شرقی'), ('azerbaijan-west', 'آذربایجان غربی'), ('khuzestan', 'خوزستان'), ('mazandaran', 'مازندران'), ('gilan', 'گیلان'), ('kermanshah', 'کرمانشاه'), ('golestan', 'گلستان'), ('semnan', 'سمنان'), ('yazd', 'یزد'), ('zanjan', 'زنجان'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('markazi', 'مرکزی'), ('hamadan', 'همدان'), ('kurdistan', 'کردستان'), ('lorestan', 'لرستان'), ('ilam', 'ایلام'), ('chahar-mahaal-bakhtiari', 'چهارمحال بختیاری'), ('kohgiluyeh-boyer-ahmad', 'کهگیلویه و بویراحمد'), ('bushehr', 'بوشهر'), ('hormozgan', 'هرمزگان'), ('sistan-baluchestan', 'سیستان و بلوچستان'), ('ardabil', 'اردبیل'), ('khorasan-north', 'خراسان شمالی'), ('khorasan-south', 'خراسان جنوبی'), ('kerman', 'کرمان')], max_length=60, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('name', models.CharField(max_length=200, verbose_name='نام نمایندگی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=60, verbose_name='تلفن')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='کد نمایندگی')),
                ('agency_type', models.CharField(choices=[('sales', 'نمایندگی فروش'), ('service', 'نمایندگی خدمات')], default='sales', max_length=10, verbose_name='نوع نمایندگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نمایندگی',
                'verbose_name_plural': 'نمایندگی\u200cها',
                'ordering': ['province', 'city'],
            },
        ),
        migrations.CreateModel(
            name='AgencySalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('store_name', models.CharField(max_length=200, verbose_name='نام فروشگاه / گالری')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('phone_landline', models.CharField(blank=True, max_length=20, verbose_name='تلفن ثابت')),
                ('phone_mobile', models.CharField(max_length=20, verbose_name='تلفن همراه')),
                ('ownership', models.CharField(choices=[('owner', 'مالک'), ('tenant', 'مستأجر')], max_length=20, verbose_name='وضعیت مالکیت')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='سابقه فعالیت (سال)')),
                ('store_address', models.TextField(verbose_name='آدرس دقیق فروشگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'درخواست نمایندگی فروش',
                'verbose_name_plural': 'درخواست\u200cهای نمایندگی فروش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('workshop_name', models.CharField(max_length=200, verbose_name='نام تعمیرگاه / واحد خدماتی')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='مدرک تحصیلی یا فنی\u200cوحرفه\u200cای')),
                ('technician_count', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد تکنسین\u200cهای فعال')),
                ('previous_brands', models.TextField(blank=True, verbose_name='سابقه همکاری با برندهای دیگر')),
                ('facilities', models.TextField(blank=True, verbose_name='امکانات موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'درخواست نمایندگی خدمات',
                'verbose_name_plural': 'درخواست\u200cهای نمایندگی خدمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
